src/Richpolis/PaginasBundle/Entity/Pagina.php
<?php

namespace Richpolis\PaginasBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Richpolis\BackendBundle\Utils\Richsys as RpsStms;

/**
 * Pagina
 *
 * @ORM\Table(name="paginas")
 * @ORM\Entity(repositoryClass="Richpolis\PaginasBundle\Repository\PaginaRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Pagina
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="pagina", type="string", length=150)
     * @Assert\NotBlank
     */
    private $pagina;
    
    /**
     * @var string
     *
     * @ORM\Column(name="imagen", type="string", length=150, nullable=true)
     */
    private $imagen;

    /**
     * @var string
     *
     * @ORM\Column(name="contenido_es", type="text", nullable=true)
     */
    private $contenidoEs;
    
    /**
     * @var string
     *
     * @ORM\Column(name="contenido_en", type="text", nullable=true)
     */
    private $contenidoEn;

    /**
     * @var integer
     *
     * @ORM\ManyToMany(targetEntity="Richpolis\GaleriasBundle\Entity\Galeria")
     * @ORM\JoinTable(name="pagina_galeria")
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private $galerias;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->galerias = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set pagina
     *
     * @param string $pagina
     * @return Pagina
     */
    public function setPagina($pagina)
    {
        $this->pagina = $pagina;

        return $this;
    }

    /**
     * Get pagina
     *
     * @return string 
     */
    public function getPagina()
    {
        return $this->pagina;
    }

    /**
     * Set contenido
     *
     * @param string $contenido
     * @return Pagina
     */
    public function setContenido($contenido,$locale)
    {
        if($locale == "es"){
            $this->contenidoEs = $contenido;
        }else if($locale == "en"){
            $this->contenidoEn = $contenido;
        }
        return $this;
    }

    /**
     * Get contenido
     *
     * @return string 
     */
    public function getContenido($locale)
    {
        if($locale == "es"){
            $contenido = $this->contenidoEs;
        }else if($locale == "en"){
            $contenido = $this->contenidoEn;
        }
        return $contenido;
    }

    /**
     * Set contenidoEs
     *
     * @param string $contenidoEs
     * @return Pagina
     */
    public function setContenidoEs($contenidoEs)
    {
        $this->contenidoEs = $contenidoEs;

        return $this;
    }

    /**
     * Get contenidoEs
     *
     * @return string 
     */
    public function getContenidoEs()
    {
        return $this->contenidoEs;
    }

    /**
     * Set contenidoEn
     *
     * @param string $contenidoEn
     * @return Pagina
     */
    public function setContenidoEn($contenidoEn)
    {
        $this->contenidoEn = $contenidoEn;

        return $this;
    }

    /**
     * Get contenidoEn
     *
     * @return string 
     */
    public function getContenidoEn()
    {
        return $this->contenidoEn;
    }

    
    /**
     * Set imagen
     *
     * @param string $imagen
     * @return Pagina
     */
    public function setImagen($imagen)
    {
        $this->imagen = $imagen;

        return $this;
    }

    /**
     * Get imagen
     *
     * @return string 
     */
    public function getImagen()
    {
        return $this->imagen;
    }

    /**
     * Add galerias
     *
     * @param \Richpolis\GaleriasBundle\Entity\Galeria $galerias
     * @return Pagina
     */
    public function addGaleria(\Richpolis\GaleriasBundle\Entity\Galeria $galerias)
    {
        $this->galerias[] = $galerias;

        return $this;
    }

    /**
     * Remove galerias
     *
     * @param \Richpolis\GaleriasBundle\Entity\Galeria $galerias
     */
    public function removeGaleria(\Richpolis\GaleriasBundle\Entity\Galeria $galerias)
    {
        $this->galerias->removeElement($galerias);
    }

    /**
     * Get galerias
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getGalerias()
    {
        return $this->galerias;
    }

    /*** uploads ***/
    
    /**
     * @Assert\File(maxSize="6000000")
     */
    public $file;
    
    /**
     * Sets file.
     *
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
        // check if we have an old image path
        if (isset($this->imagen)) {
            // store the old name to delete after the update
            $this->temp = $this->imagen;
            $this->imagen = null;
        } else {
            $this->imagen = 'initial';
        }
    }
    
    /**
     * Get file.
     *
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }
    
   /**
    * @ORM\PrePersist()
    * @ORM\PreUpdate()
    */
    public function preUpload()
    {
      $var = true;  
      if (null !== $this->getFile()) {
            // do whatever you want to generate a unique name
            $filename = sha1(uniqid(mt_rand(), true));
            $this->imagen = $filename.'.'.$this->getFile()->guessExtension();
        }
    }

    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */
    public function upload()
    {
      $var = true;  
      if (null === $this->getFile()) {
            return;
        }

        // if there is an error when moving the file, an exception will
        // be automatically thrown by move(). This will properly prevent
        // the entity from being persisted to the database on error
        $this->getFile()->move($this->getUploadRootDir(), $this->imagen);

        // check if we have an old image
        if (isset($this->temp)) {
            // delete the old image
            unlink($this->getUploadRootDir().'/'.$this->temp);
            // clear the temp image path
            $this->temp = null;
        }
        
        $this->file = null;
    }

    /**
    * @ORM\PostRemove
    */
    public function removeUpload()
    {
      if ($file = $this->getAbsolutePath()) {
        if(file_exists($file)){
            unlink($file);
        }
      }
    }
    
    protected function getUploadDir()
    {
        return '/uploads/paginas';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web'.$this->getUploadDir();
    }
    
    public function getWebPath()
    {
        return null === $this->imagen ? null : $this->getUploadDir().'/'.$this->imagen;
    }
    
    public function getAbsolutePath()
    {
        return null === $this->imagen ? null : $this->getUploadRootDir().'/'.$this->imagen;
    }

    public function getDescripcionCorta(){
        return RpsStms::cut_string2(RpsStms::strip_html_tags($this->getContenidoEs()),250);
    }

    
}

src/Richpolis/PaginasBundle/Controller/PaginaController.php
<?php

namespace Richpolis\PaginasBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;

use Richpolis\PaginasBundle\Entity\Pagina;
use Richpolis\PaginasBundle\Form\PaginaType;

use Richpolis\BackendBundle\Utils\Richsys as RpsStms;

use Richpolis\BackendBundle\Utils\qqFileUploader;
use Richpolis\GaleriasBundle\Entity\Galeria;


/**
 * Pagina controller.
 *
 * @Route("/paginas")
 */
class PaginaController extends Controller
{

    /**
     * Lists all Pagina entities.
     *
     * @Route("/", name="paginas")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('PaginasBundle:Pagina')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new Pagina entity.
     *
     * @Route("/", name="paginas_create")
     * @Method("POST")
     * @Template("PaginasBundle:Pagina:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Pagina();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('paginas_show', array('id' => $entity->getId())));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
            'errores' => RpsStms::getErrorMessages($form)
        );
    }

    /**
    * Creates a form to create a Pagina entity.
    *
    * @param Pagina $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createCreateForm(Pagina $entity)
    {
        $form = $this->createForm(new PaginaType(), $entity, array(
            'action' => $this->generateUrl('paginas_create'),
            'method' => 'POST',
        ));

        //$form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Pagina entity.
     *
     * @Route("/new", name="paginas_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Pagina();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
            'errores' => RpsStms::getErrorMessages($form)
        );
    }

    /**
     * Finds and displays a Pagina entity.
     *
     * @Route("/{id}", name="paginas_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('PaginasBundle:Pagina')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Pagina entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
            'get_galerias' =>$this->generateUrl('paginas_galerias',array('id'=>$entity->getId()),true),
            'post_galerias' =>$this->generateUrl('paginas_galerias_upload', array('id'=>$entity->getId()),true),
			'post_galerias_link_video' =>$this->generateUrl('paginas_galerias_link_video', array('id'=>$entity->getId()),true),
            'url_delete' => $this->generateUrl('paginas_galerias_delete',array('id'=>$entity->getId(),'idGaleria'=>'0'),true),
        );
    }

    /**
     * Displays a form to edit an existing Pagina entity.
     *
     * @Route("/{id}/edit", name="paginas_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('PaginasBundle:Pagina')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Pagina entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'errores' => RpsStms::getErrorMessages($editForm)
        );
    }

    /**
    * Creates a form to edit a Pagina entity.
    *
    * @param Pagina $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Pagina $entity)
    {
        $form = $this->createForm(new PaginaType(), $entity, array(
            'action' => $this->generateUrl('paginas_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        //$form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Pagina entity.
     *
     * @Route("/{id}", name="paginas_update")
     * @Method("PUT")
     * @Template("PaginasBundle:Pagina:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('PaginasBundle:Pagina')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Pagina entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);
        //$editForm->submit($request->request->get($editForm->getName()),false);

        if ($editForm->isValid()) {
            $entity->preUpload();
            $entity->upload();
            $em->flush();

            return $this->redirect($this->generateUrl('paginas_show', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'form'        => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
            'errores'     => RpsStms::getErrorMessages($editForm)
        );
    }
    
    /**
     * Deletes a Pagina entity.
     *
     * @Route("/{id}", name="paginas_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        //if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('PaginasBundle:Pagina')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Pagina entity.');
            }

            $em->remove($entity);
            $em->flush();
        //}

        return $this->redirect($this->generateUrl('paginas'));
    }

    /**
     * Creates a form to delete a Pagina entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('paginas_delete', array('id' => $id)))
            ->setMethod('DELETE')
            /*->add('submit', 'submit', array(
                'label' => 'Eliminar',
                'attr'=>array(
                    'class'=>'btn btn-danger'
            )))*/
            ->getForm()
        ;
    }
    
    /**
     * Lists all Pagina galerias entities.
     *
     * @Route("/{id}/galerias", name="paginas_galerias")
     * @Method("GET")
     */
    public function galeriasAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $pagina = $em->getRepository('PaginasBundle:Pagina')->find($id);
        
        $galerias = $pagina->getGalerias();
        $get_galerias = $this->generateUrl('paginas_galerias',array('id'=>$pagina->getId()),true);
        $post_galerias = $this->generateUrl('paginas_galerias_upload', array('id'=>$pagina->getId()),true);
		$post_galerias_link_video = $this->generateUrl('paginas_galerias_link_video', array('id'=>$pagina->getId()),true);
        $url_delete = $this->generateUrl('paginas_galerias_delete',array('id'=>$pagina->getId(),'idGaleria'=>'0'),true);
        
        return $this->render('GaleriasBundle:Galeria:galerias.html.twig', array(
            'galerias'=>$galerias,
            'get_galerias' =>$get_galerias,
            'post_galerias' =>$post_galerias,
			'post_galerias_link_video' =>$post_galerias_link_video,
            'url_delete' => $url_delete,
        ));
    }
    
    /**
     * Crea una galeria de una pagina.
     *
     * @Route("/{id}/galerias", name="paginas_galerias_upload")
     * @Method("POST")
     */
    public function galeriasUploadAction(Request $request,$id){
        $em = $this->getDoctrine()->getManager();
        $pagina=$em->getRepository('PaginasBundle:Pagina')->find($id);
       
        if(!$request->request->has('tipoArchivo')){ 
            // list of valid extensions, ex. array("jpeg", "xml", "bmp")
            $allowedExtensions = array("jpeg","png","gif","jpg");
            // max file size in bytes
            $sizeLimit = 6 * 1024 * 1024;
            $uploader = new qqFileUploader($allowedExtensions, $sizeLimit,$request->server);
            $uploads= $this->container->getParameter('richpolis.uploads');
            $result = $uploader->handleUpload($uploads."/galerias/");
            // to pass data through iframe you will need to encode all html tags
            /*****************************************************************/
            //$file = $request->getParameter("qqfile");

src/Richpolis/PaginasBundle/Resources/views/Pagina/edit.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets%}
<!-- Stylesheets -->
<link rel="stylesheet" href="{{asset('css/bootstrap.css')}}">
<!-- Font awesome icon -->
<link rel="stylesheet" href="{{asset('css/font-awesome.css')}}"> 
<!-- jQuery UI -->
<link rel="stylesheet" href="{{asset('css/jquery-ui-1.9.2.custom.min.css')}}"> 
<!-- Calendar -->
<link rel="stylesheet" href="{{asset('css/fullcalendar.css')}}">
<!-- prettyPhoto -->
<link rel="stylesheet" href="{{asset('css/prettyPhoto.css')}}">  
<!-- Star rating -->
<link rel="stylesheet" href="{{asset('css/rateit.css')}}">
<!-- Date picker -->
<link rel="stylesheet" href="{{asset('css/bootstrap-datetimepicker.min.css')}}">
<!-- CLEditor -->
<link rel="stylesheet" href="{{asset('css/jquery.cleditor.css')}}"> 
<!-- Uniform -->
<link rel="stylesheet" href="{{asset('css/uniform.default.html')}}"> 
<!-- Uniform -->
<link rel="stylesheet" href="{{asset('css/daterangepicker-bs3.css')}}" />
<!-- Bootstrap toggle -->
<link rel="stylesheet" href="{{asset('css/bootstrap-switch.css')}}">
<!-- Main stylesheet -->
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<!-- Widgets stylesheet -->
<link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
<!-- Gritter Notifications stylesheet -->
<link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}">
<!-- jQuery Validation Engine stylesheet -->
<link rel="stylesheet" href="{{asset('css/validationEngine.jquery.css')}}">

{% endblock %}

{% block mainbar %}
<!-- Main bar -->
<div class="mainbar">

    <!-- Page heading -->
    <div class="page-head">
        <h2 class="pull-left">Paginas</h2>
        <div class="clearfix"></div>
        <!-- Breadcrumb -->
        <div class="bread-crumb">
            <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a> 
            <!-- Divider -->
            <span class="divider">/</span> 
            <a href="{{path('paginas_edit',{'id':entity.id})}}" class="bread-current">Editar pagina</a>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- Page heading ends -->

    <!-- Matter -->
    <div class="matter">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="widget">

                        <div class="widget-head">
                            <div class="pull-left">Editar pagina "{{entity.pagina}}"</div>
                            <!--div class="widget-icons pull-right">
                                <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                                <a href="#" class="wsettings"><i class="fa fa-wrench"></i></a>  
                                <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                            </div-->
                            <div class="clearfix"></div>
                        </div>

                        <div class="widget-content">
                            <div class="padd">
                                <!-- Form starts.  -->
                                <form action="{{ path('paginas_update', { 'id': entity.id }) }}" class="validate" id="formPaginas"  method="post" {{ form_enctype(form)}}>
                                    <input name="_method" value="put" type="hidden"/>
                                    {{form_widget(form)}}
                                </form>
                                <br/>
                                {% if entity.imagen | length > 0 %}
                                    <img src="{{ entity.webPath }}" style="max-width: 400px;"/>
                                {% else %}    
                                    sin imagen
                                {% endif %}
                                
                            </div>
                        </div>
                        <div class="widget-foot">
                            <button id="botonRegresar" class="btn btn-default">Regresar</button>
                            <button id="botonGuardar" class="btn btn-primary">Guardar cambios</button>
                            <div style="float: left; margin-right: 3px;">
                            {{form_widget(delete_form)}}
                            </div>        
                        </div>
                    </div>  

                </div>
            </div>
        </div>
    </div>
    <!-- Matter ends -->
</div>
<!-- Mainbar ends -->           
<div class="clearfix"></div>
{% endblock %}

{% block javascripts %}
  {{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<script src="{{asset('js/fullcalendar.min.js')}}"></script> <!-- Full Google Calendar - Calendar -->
<script src="{{asset('js/jquery.rateit.min.js')}}"></script> <!-- RateIt - Star rating -->
<script src="{{asset('js/jquery.prettyPhoto.js')}}"></script> <!-- prettyPhoto -->

<!-- jQuery Flot -->
<script src="{{asset('js/excanvas.min.js')}}"></script>
<script src="{{asset('js/jquery.flot.js')}}"></script>
<script src="{{asset('js/jquery.flot.resize.js')}}"></script>
<script src="{{asset('js/jquery.flot.pie.js')}}"></script>
<script src="{{asset('js/jquery.flot.stack.js')}}"></script>

<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/languages/jquery.validationEngine-es.js')}}"></script> <!-- jQuery Validation Engine Language File -->
<script src="{{asset('js/jquery.validationEngine.js')}}"></script> <!-- jQuery Validation Engine -->

<!-- Daterangepicker -->
<script src="{{asset('js/moment.min.js')}}"></script>
<script src="{{asset('js/daterangepicker.js')}}"></script>


<script src="{{asset('js/sparklines.js')}}"></script> <!-- Sparklines -->
<script src="{{asset('js/jquery.gritter.min.js')}}"></script> <!-- jQuery Gritter -->
<script src="{{asset('js/jquery.cleditor.min.js')}}"></script> <!-- CLEditor -->
<script src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script> <!-- Date picker -->
<script src="{{asset('js/jquery.uniform.min.html')}}"></script> <!-- jQuery Uniform -->
<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->
<script src="{{asset('js/bootstrap-switch.min.js')}}"></script> <!-- Bootstrap Toggle -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->
<script src="{{asset('js/charts.js')}}"></script> <!-- Charts & Graphs -->


<script>
$(document).ready(function(){   
  $(".validate").validationEngine();

  $("#botonRegresar").on("click",function(){
    location.href="{{path('paginas')}}";
  });
  
  $("#botonGuardar").on("click",function(){
    $("#formPaginas").submit();
  });
  
  {% if errores | length > 0 %}
    {% for error in errores %}
       noty({
          text: '{{ error }}',
          layout:'topRight',
          type:'error',
          timeout:2000
      }); 
    {% endfor %}    
  {% endif %}
  
});

</script>
{{ tinymce_init() }}
{% endblock %}