src/Richpolis/BackendBundle/Entity/Configuraciones.php
<?php

namespace Richpolis\BackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Configuraciones
 *
 * @ORM\Table(name="configuraciones")
 * @ORM\Entity(repositoryClass="Richpolis\BackendBundle\Repository\ConfiguracionesRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Configuraciones
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="configuracion", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $configuracion;

    /**
     * @var integer
     *
     * @ORM\Column(name="tipo_archivo", type="integer", length=1)
     * @Assert\NotBlank()
     */
    private $tipoConfiguracion;

    /**
     * @var string
     *
     * @ORM\Column(name="texto", type="text",nullable=true)
     */
    private $texto;
    
    /**
     * @var boolean
     *
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;    

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255,nullable=true)
     */
    private $slug;

    static public $IMAGEN=1;
    static public $LINK_VIDEO=2;
    static public $TEXTO_LARGO=3;
    static public $TEXTO_CORTO=4;
    
    
    
    static private $sCategorias=array(
        1=>'Imagen',
        2=>'Link_video',
        3=>'Texto largo',
        4=>'Texto corto',
    );
    
    public function getStringTipoConfiguracion(){
        return self::$sCategorias[$this->getTipoConfiguracion()];
    }

    static function getArrayTipoConfiguracion(){
        return self::$sCategorias;
    }

    static function getPreferedTipoConfiguracion(){
        return array(self::$TEXTO_CORTO);
    }
    
    public function __construct() {
        $this->isActive = true;
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set configuracion
     *
     * @param string $configuracion
     * @return Configuraciones
     */
    public function setConfiguracion($configuracion)
    {
        $this->configuracion = $configuracion;
        
        return $this;
    }

    /**
     * Get configuracion
     *
     * @return string 
     */
    public function getConfiguracion()
    {
        return $this->configuracion;
    }

    /**
     * Set tipo
     *
     * @param integer $tipo
     * @return Configuraciones
     */
    public function setTipoConfiguracion($tipo)
    {
        $this->tipoConfiguracion = $tipo;
    
        return $this;
    }

    /**
     * Get tipo
     *
     * @return integer 
     */
    public function getTipoConfiguracion()
    {
        return $this->tipoConfiguracion;
    }
    
    /**
     * Set texto
     *
     * @param string $texto
     * @return Configuraciones
     */
    public function setTexto($texto)
    {
        $this->texto = $texto;
    
        return $this;
    }

    /**
     * Get texto
     *
     * @return string 
     */
    public function getTexto()
    {
        return $this->texto;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Configuraciones
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    
        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }
    
    /*
     * Slugable
     */
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function setSlugAtValue()
    {
        $this->slug = \Richpolis\BackendBundle\Utils\Richsys::slugify($this->getConfiguracion());
    }
    
    
    /**
    ** @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preSaveLinkVideo()
    {
      if ($this->getTipoConfiguracion()==self::$LINK_VIDEO) {
        $infoVideo=  \Richpolis\BackendBundle\Utils\Richsys::getTitleAndImageVideoYoutube($this->getTexto());
        $this->setTexto($infoVideo['urlVideo']);
      }
    }
    
    /*
     * uploads file
     */
    
    public $file;
    
    /**
    * @ORM\PrePersist
    * @ORM\PreUpdate
    */
    public function preUpload()
    {
      if (null !== $this->file) {
        // do whatever you want to generate a unique name
        $this->texto = uniqid().'.'.$this->file->guessExtension();
      }
    }

    /**
    * @ORM\PostPersist
    * @ORM\PostUpdate
    */
    public function upload()
    {
      if (null === $this->file) {
        return;
      }

      // if there is an error when moving the file, an exception will
      // be automatically thrown by move(). This will properly prevent
      // the entity from being persisted to the database on error
      $this->file->move($this->getUploadRootDir(), $this->texto);

      
      unset($this->file);
    }

    /**
    * @ORM\PostRemove
    */
    public function removeUpload()
    {
      if($this->getTipoConfiguracion()==self::$IMAGEN){  
        if ($file = $this->getAbsolutePath()) {
          if(file_exists($file)){
              unlink($file);
          }
        }
      }
    }
    
    protected function getUploadDir()
    {
        return '/uploads/configuraciones';
    }

    protected function getUploadRootDir()
    {
        return __DIR__.'/../../../../web'.$this->getUploadDir();
    }
    
    protected function getThumbnailRootDir()
    {
        return __DIR__.'/../../../../web'.$this->getUploadDir().'/thumbnails';
    }
        
    public function getWebPath()
    {
        return null === $this->texto ? null : $this->getUploadDir().'/'.$this->texto;
    }
    
    public function getAbsolutePath()
    {
        return null === $this->texto ? null : $this->getUploadRootDir().'/'.$this->texto;
    }
    
    public function isImagen(){
        return $this->getTipoConfiguracion() == Configuraciones::$IMAGEN;
    }
    
    public function isLinkVideo(){
        return $this->getTipoConfiguracion() == Configuraciones::$LINK_VIDEO;
    }

    /**
     * Set isActive
     *
     * @param boolean $isActive
     * @return Configuraciones
     */
    public function setIsActive($isActive)
    {
        $this->isActive = $isActive;
    
        return $this;
    }

    /**
     * Get isActive
     *
     * @return boolean 
     */
    public function getIsActive()
    {
        return $this->isActive;
    }
}

src/Richpolis/BackendBundle/Entity/Usuario.php
<?php

namespace Richpolis\BackendBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
//use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;

use JMS\Serializer\Annotation as Serializer;



/**
 * Usuarios
 *
 * @ORM\Table(name="usuarios")
 * @ORM\Entity(repositoryClass="Richpolis\BackendBundle\Repository\UsuariosRepository")
 * @ORM\HasLifecycleCallbacks()
 * 
 * @Serializer\ExclusionPolicy("all")
 */
class Usuario implements UserInterface, \Serializable
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * 
     * @Serializer\Expose
     * @Serializer\Type("integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="username", type="string", length=100, nullable=false)
     * @Assert\NotBlank()
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     * 
     */
    private $username;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255, nullable=false)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=100, nullable=false)
     * @Assert\NotBlank()
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     */
    private $email;
    
    /**
     * @var string
     *
     * @ORM\Column(name="salt", type="string", length=255)
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     */
    private $salt;
    
    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     * 
     */
    private $nombre;
    
    /**
     * @var string
     *
     * @ORM\Column(name="twitter", type="string", length=255, nullable=true)
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     * 
     */
    private $twitter;
    
    /**
     * @var string
     *
     * @ORM\Column(name="facebook", type="string", length=255, nullable=true)
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     * 
     */
    private $facebook;
    
    /**
     * @var string
     *
     * @ORM\Column(name="grupo", type="string", length=100, nullable=false)
     * 
     * @Serializer\Expose
     * @Serializer\Type("integer")
     * 
     */
    private $grupo;
    
    /**
     * @var string
     *
     * @ORM\Column(name="imagen", type="string", length=255, nullable=true)
     * 
     * @Serializer\Expose
     * @Serializer\Type("string")
     * 
     */
    private $imagen;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     * 
     * @Serializer\Expose
     * @Serializer\Type("DateTime")
     * 
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=false)
     * 
     * @Serializer\Expose
     * @Serializer\Type("DateTime")
     * 
     */
    private $updatedAt;
    
    /**
     * @var integer
     *
     * @ORM\OneToMany(targetEntity="Richpolis\PublicacionesBundle\Entity\Publicacion", mappedBy="usuario")
     */
    private $publicaciones;
    
    
    const GRUPO_USUARIOS=1;
    const GRUPO_ADMIN=2;
    const GRUPO_SUPER_ADMIN=3;
    
 
    public function __toString(){
        return $this->getUsername();
    }
    
    /**
     * @Serializer\VirtualProperty
     * @Serializer\SerializedName("stringGrupo")
     * 
     */
    public function getStringTipoGrupo(){
        $arreglo = $this->getArrayTipoGrupo();
        return $arreglo[$this->getGrupo()];
    }

    static function getArrayTipoGrupo(){
        $sTipoGrupo=array(
            self::GRUPO_USUARIOS=>'Usuarios',
            self::GRUPO_ADMIN=>'Administrador',
            self::GRUPO_SUPER_ADMIN=>'Superadmin',
        );
        return $sTipoGrupo;
    }

    static function getPreferedTipoGrupo(){
        return array(self::GRUPO_USUARIOS);
    }


    public function __construct()
    {
        // may not be needed, see section on salt below
        $this->salt = base_convert(sha1(uniqid(mt_rand(), true)), 16, 36);
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set username
     *
     * @param string $username
     * @return Usuarios
     */
    public function setUsername($username)
    {
        $this->username = $username;
    
        return $this;
    }

    /**
     * Get username
     *
     * @return string 
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * Set password
     *
     * @param string $password
     * @return Usuarios
     */
    public function setPassword($password)
    {
        $this->password = $password;
    
        return $this;
    }

    /**
     * Get password
     *
     * @return string 
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set email
     *
     * @param string $email
     * @return Usuarios
     */
    public function setEmail($email)
    {
        $this->email = $email;
    
        return $this;
    }

    /**
     * Get email
     *
     * @return string 
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set nombre
     *
     * @param string $nombre
     * @return Usuarios
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;
    
        return $this;
    }

    /**
     * Get nombre
     *
     * @return string 
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set grupo
     *
     * @param string $grupo
     * @return Usuarios
     */
    public function setGrupo($grupo)
    {
        $this->grupo = $grupo;
    
        return $this;
    }

    /**
     * Get grupo
     *
     * @return string 
     */
    public function getGrupo()
    {
        return $this->grupo;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Usuarios
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    
        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Usuarios
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;
    
        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /*
     * Timestable
     */
    
    /**
     ** @ORM\PrePersist
     */
    public function setCreatedAtValue()
    {
        if(!$this->getCreatedAt())
        {
          $this->createdAt = new \DateTime();
        }
        if(!$this->getUpdatedAt())
        {
          $this->updatedAt = new \DateTime();
        }
    }

    /**
     * @ORM\PreUpdate
     */
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTime();
    }
    
    function eraseCredentials()
    {
    }

    function getRoles()
    {
        if($this->getGrupo() == self::GRUPO_USUARIOS){
            return array('ROLE_USER','ROLE_API');
        }elseif($this->getGrupo() == self::GRUPO_SUPER_ADMIN){
            return array('ROLE_SUPER_ADMIN','ROLE_API');
        }else{
            return array('ROLE_ADMIN','ROLE_API');
        }
    }

    /**
     * Set salt
     *
     * @param string $salt
     * @return Usuario
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;
    
        return $this;
    }

    /**
     * Get salt
     *
     * @return string 
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * @see \Serializable::serialize()
     */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->username,
            $this->twitter,
            $this->facebook,
            $this->email
        ));
    }

    /**
     * @see \Serializable::unserialize()
     */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->username,
            $this->twitter,
            $this->facebook,
            $this->email
        ) = unserialize($serialized);
    }

    /**
     * Set twitter
     *
     * @param string $twitter
     * @return Usuario
     */
    public function setTwitter($twitter)
    {
        $this->twitter = $twitter;

        return $this;
    }

    /**
     * Get twitter
     *
     * @return string 
     */
    public function getTwitter()
    {
        return $this->twitter;
    }

    /**
     * Set facebook
     *
     * @param string $facebook
     * @return Usuario
     */
    public function setFacebook($facebook)
    {
        $this->facebook = $facebook;

        return $this;
    }

    /**
     * Get facebook
     *
     * @return string 
     */
    public function getFacebook()
    {
        return $this->facebook;
    }

    /**
     * Add publicaciones
     *
     * @param \Richpolis\PublicacionesBundle\Entity\Publicacion $publicaciones
     * @return Usuario
     */
    public function addPublicacione(\Richpolis\PublicacionesBundle\Entity\Publicacion $publicaciones)
    {
        $this->publicaciones[] = $publicaciones;

        return $this;
    }

    /**
     * Remove publicaciones
     *
     * @param \Richpolis\PublicacionesBundle\Entity\Publicacion $publicaciones
     */

src/Richpolis/BackendBundle/Resources/views/Usuario/index.html.twig
{% extends 'BackendBundle::layout.html.twig' %}

{% block stylesheets%}
	<!-- Stylesheets -->
  <link rel="stylesheet" href="{{asset('css/bootstrap.css')}}">
  <!-- Font awesome icon -->
  <link rel="stylesheet" href="{{asset('css/font-awesome.css')}}"> 
  <!-- jQuery UI -->
  <link rel="stylesheet" href="{{asset('css/jquery-ui-1.9.2.custom.min.css')}}"> 
  <!-- Calendar -->
  <link rel="stylesheet" href="{{asset('css/fullcalendar.css')}}">
  <!-- prettyPhoto -->
  <link rel="stylesheet" href="{{asset('css/prettyPhoto.css')}}">  
  <!-- Star rating -->
  <link rel="stylesheet" href="{{asset('css/rateit.css')}}">
  <!-- Date picker -->
  <link rel="stylesheet" href="{{asset('css/bootstrap-datetimepicker.min.css')}}">
  <!-- CLEditor -->
  <link rel="stylesheet" href="{{asset('css/jquery.cleditor.css')}}"> 
  <!-- Uniform -->
  <link rel="stylesheet" href="{{asset('css/uniform.default.html')}}"> 
  <!-- Uniform -->
  <link rel="stylesheet" href="{{asset('css/daterangepicker-bs3.css')}}" />
  <!-- Bootstrap toggle -->
  <link rel="stylesheet" href="{{asset('css/bootstrap-switch.css')}}">
    <!-- Bootstrap toggle -->
  <link rel="stylesheet" href="{{asset('js/datatables/css/dataTables.bootstrap.css')}}">
  <!-- Main stylesheet -->
  <link rel="stylesheet" href="{{asset('css/style.css')}}">
  <!-- Widgets stylesheet -->
  <link rel="stylesheet" href="{{asset('css/widgets.css')}}">   
    <!-- Gritter Notifications stylesheet -->
  <link rel="stylesheet" href="{{asset('css/jquery.gritter.css')}}"> 

{% endblock %}

{% block mainbar %}
          <!-- Main bar -->
    <div class="mainbar">
      
      <!-- Page heading -->
      <div class="page-head">
        <h2 class="pull-left">Usuarios</h2>
        <div class="clearfix"></div>
        <!-- Breadcrumb -->
        <div class="bread-crumb">
          <a href="{{path('backend_homepage')}}"><i class="fa fa-home"></i>Dashboard</a--> 
          <Divider>
          <span class="divider">/</span> 
          <a href="{{path('users')}}" class="bread-current">Usuarios</a>
          {% if is_granted('ROLE_SUPER_ADMIN') %}
          <a href="{{path('users_new')}}" class="btn btn-info pull-right" style="color: white; margin-left: 5px;">Crear usuario</a>
          {% endif %}
        </div>
        
        <div class="clearfix"></div>

      </div>
      <!-- Page heading ends -->

      <!-- Matter -->

      <div class="matter">
        <div class="container">

          <!-- Table -->

            <div class="row">

              <div class="col-md-12">

                <div class="widget">

                <div class="widget-head">
                  <div class="pull-left">Registro de Usuarios</div>
                  <!--div class="widget-icons pull-right">
                    <a href="#" class="wminimize"><i class="fa fa-chevron-up"></i></a>
                    <a href="#" class="wsettings"><i class="fa fa-wrench"></i></a>  
                    <a href="#" class="wclose"><i class="fa fa-times"></i></a>
                  </div-->  
                  <div class="clearfix"></div>
                </div>

                  <div class="widget-content">

                    <table id="datatable" class="table table-striped table-bordered table-hover">
                      <thead>
                        <tr>
                            <th>Id</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Nombre</th>
                            <th>Grupo</th>
                            <th>Creado</th>
                            <th>Actualizado</th>
                            <th>Actions</th>
                        </tr>
                      </thead>
                      <tbody>
                      {% for entity in entities %}
                            <tr id="registro-{{entity.id}}">
                                <td>{{ entity.id }}</td>
                                <td>{{ entity.username }}</td>
                                <td>{{ entity.email }}</td>
                                <td>{{ entity.nombre }}</td>
                                <td>{{ entity.stringTipoGrupo }}</td>
                                <td>{% if entity.createdAt %}{{ entity.createdAt|date('Y-m-d H:i:s') }}{% endif %}</td>
                                <td>{% if entity.updatedAt %}{{ entity.updatedAt|date('Y-m-d H:i:s') }}{% endif %}</td>
                                <td>
                                    <button onclick="javascript:editarRegistro('{{ path('users_edit', { 'id': entity.id }) }}')" class="btn btn-xs btn-warning"><i class="fa fa-pencil"></i> </button>
									<button onclick="javascript:editarRegistro('{{ path('users_show', { 'id': entity.id }) }}','#registro-{{entity.id}}')" class="btn btn-xs btn-info"><i class="fa fa-folder-open"></i> </button>
                                    <button onclick="javascript:eliminarRegistro('{{ path('users_delete', { 'id': entity.id }) }}','#registro-{{entity.id}}')" class="btn btn-xs btn-danger"><i class="fa fa-times"></i></button>
                                </td>
                                
                            </tr>
                        {% endfor %}

                      </tbody>
                    </table>

                    <div class="widget-foot">
                       <br><br>
                      <div class="clearfix"></div>
                    </div>

                  </div>

                </div>

              </div>

            </div>

        </div>
      </div>

    <!-- Matter ends -->

    </div>

   <!-- Mainbar ends -->        
   <div class="clearfix"></div>
  
{% endblock %}

{% block javascripts %}
  {{ parent() }}

<script src="{{asset('js/jquery-ui-1.9.2.custom.min.js')}}"></script> <!-- jQuery UI -->
<script src="{{asset('js/fullcalendar.min.js')}}"></script> <!-- Full Google Calendar - Calendar -->
<script src="{{asset('js/jquery.rateit.min.js')}}"></script> <!-- RateIt - Star rating -->
<script src="{{asset('js/jquery.prettyPhoto.js')}}"></script> <!-- prettyPhoto -->

<!-- jQuery Flot -->
<script src="{{asset('js/excanvas.min.js')}}"></script>
<script src="{{asset('js/jquery.flot.js')}}"></script>
<script src="{{asset('js/jquery.flot.resize.js')}}"></script>
<script src="{{asset('js/jquery.flot.pie.js')}}"></script>
<script src="{{asset('js/jquery.flot.stack.js')}}"></script>

<!-- jQuery Notification - Noty -->
<script src="{{asset('js/jquery.noty.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/themes/default.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/bottom.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/topRight.js')}}"></script> <!-- jQuery Notify -->
<script src="{{asset('js/layouts/top.js')}}"></script> <!-- jQuery Notify -->
<!-- jQuery Notification ends -->

<script src="{{asset('js/datatables/js/jquery.dataTables.js')}}"></script>

<script src="{{asset('js/sparklines.js')}}"></script> <!-- Sparklines -->
<script src="{{asset('js/jquery.cleditor.min.js')}}"></script> <!-- CLEditor -->
<script src="{{asset('js/bootstrap-datetimepicker.min.js')}}"></script> <!-- Date picker -->
<script src="{{asset('js/jquery.uniform.min.html')}}"></script> <!-- jQuery Uniform -->
<script src="{{asset('js/jquery.slimscroll.min.js')}}"></script> <!-- jQuery SlimScroll -->
<script src="{{asset('js/bootstrap-switch.min.js')}}"></script> <!-- Bootstrap Toggle -->
<script src="{{asset('js/bootbox.min.js')}}"></script> <!-- Filter for support page -->
<script src="{{asset('js/custom.js')}}"></script> <!-- Custom codes -->
<script src="{{asset('js/charts.js')}}"></script> <!-- Charts & Graphs -->


<script>
var editarRegistro = function(url){
        location.href=url;
};
    
var eliminarRegistro = function(url,idRegistro){
  {% if is_granted('ROLE_SUPER_ADMIN') %}
    bootbox.confirm("Esta seguro de eliminar el registro?", function(result) {
      if(result){
         location.href=url;
      }
    });
  {% else %}
    noty({text: 'No tienes los permisos suficientes para realizar esta accion',layout:'bottom', type:'warning', timeout:2000 });
  {% endif %}      
};
    
$(document).ready(function() {
    $('#datatable').dataTable({
        "sPaginationType": "full_numbers",
        "sNext":"Siguiente",
        "sLast":"Ultimo",
        "sFirst":"Primero",
        "sPrevious": "Anterior",
    });
});
</script>

    
{% endblock %}